name: build
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            path: main
      - name: Build on Arduino CLI
        run: bash ci/build-arduino.sh
